"""initial V1.3 schema

Revision ID: 20260825_0001
Revises: 
Create Date: 2026-08-25 12:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '20260825_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _json_document():
    return sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('job_type', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('parent_job_id', sa.Uuid(), nullable=True),
    sa.Column('config_snapshot', _json_document(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['ai_jobs.id'], name=op.f('fk_ai_jobs_parent_job_id_ai_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_jobs'))
    )
    op.create_index(op.f('ix_ai_jobs_organization_unit_id'), 'ai_jobs', ['organization_unit_id'], unique=False)
    op.create_index('ix_ai_jobs_resource', 'ai_jobs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_ai_jobs_status_updated', 'ai_jobs', ['status', 'updated_at'], unique=False)
    op.create_table('audio_records',
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_code', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('upload_status', sa.String(length=32), nullable=False),
    sa.Column('business_status', sa.String(length=32), nullable=False),
    sa.Column('current_transcript_version_id', sa.Uuid(), nullable=True),
    sa.Column('current_summary_version_id', sa.Uuid(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_records')),
    sa.UniqueConstraint('object_key', name=op.f('uq_audio_records_object_key'))
    )
    op.create_index('ix_audio_records_org_shift', 'audio_records', ['organization_unit_id', 'shift_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('before_data', _json_document(), nullable=True),
    sa.Column('after_data', _json_document(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_unit_id'), 'audit_logs', ['organization_unit_id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id', 'occurred_at'], unique=False)
    op.create_table('business_config_versions',
    sa.Column('config_code', sa.String(length=100), nullable=False),
    sa.Column('config_type', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', _json_document(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_config_versions')),
    sa.UniqueConstraint('config_code', 'version', name='uq_business_config_version')
    )
    op.create_index(op.f('ix_business_config_versions_config_code'), 'business_config_versions', ['config_code'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', _json_document(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('actor_id', 'operation', 'idempotency_key', name='uq_idempotency_key')
    )
    op.create_table('inspection_records',
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('pipeline_name', sa.String(length=200), nullable=True),
    sa.Column('equipment_name', sa.String(length=200), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_records'))
    )
    op.create_index('ix_inspection_org_time', 'inspection_records', ['organization_unit_id', 'inspected_at'], unique=False)
    op.create_table('manual_operation_records',
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.String(length=40), nullable=False),
    sa.Column('record_type', sa.String(length=60), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('business_status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_operation_records'))
    )
    op.create_index('ix_manual_operation_org_time', 'manual_operation_records', ['organization_unit_id', 'occurred_at'], unique=False)
    op.create_table('model_aliases',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_snapshot', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', _json_document(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_aliases')),
    sa.UniqueConstraint('code', name=op.f('uq_model_aliases_code'))
    )
    op.create_table('operation_reports',
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('scope_filter', _json_document(), nullable=False),
    sa.Column('scope_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('published_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_reports')),
    sa.UniqueConstraint('report_type', 'business_date', 'organization_unit_id', 'scope_digest', name='uq_operation_report_scope')
    )
    op.create_index('ix_operation_reports_status', 'operation_reports', ['organization_unit_id', 'status', 'business_date'], unique=False)
    op.create_table('organization_units',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_type', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_units.id'], name=op.f('fk_organization_units_parent_id_organization_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_units')),
    sa.UniqueConstraint('code', name=op.f('uq_organization_units_code'))
    )
    op.create_index(op.f('ix_organization_units_path'), 'organization_units', ['path'], unique=False)
    op.create_table('production_events',
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_status', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_events'))
    )
    op.create_index(op.f('ix_production_events_event_type'), 'production_events', ['event_type'], unique=False)
    op.create_index('ix_production_events_org_time', 'production_events', ['organization_unit_id', 'occurred_at'], unique=False)
    op.create_index('ix_production_events_status', 'production_events', ['business_status', 'updated_at'], unique=False)
    op.create_table('prompt_template_versions',
    sa.Column('template_code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_template', sa.Text(), nullable=False),
    sa.Column('output_schema', _json_document(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_template_versions')),
    sa.UniqueConstraint('template_code', 'version', name='uq_prompt_template_version')
    )
    op.create_index(op.f('ix_prompt_template_versions_template_code'), 'prompt_template_versions', ['template_code'], unique=False)
    op.create_table('role_definitions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', _json_document(), nullable=False),
    sa.Column('system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_role_definitions_code'))
    )
    op.create_table('upload_sessions',
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('client_sha256', sa.String(length=64), nullable=True),
    sa.Column('server_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_sessions')),
    sa.UniqueConstraint('object_key', name=op.f('uq_upload_sessions_object_key'))
    )
    op.create_index(op.f('ix_upload_sessions_organization_unit_id'), 'upload_sessions', ['organization_unit_id'], unique=False)
    op.create_index('ix_upload_sessions_resource', 'upload_sessions', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_status'), 'upload_sessions', ['status'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('workflow_type', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_node', sa.String(length=100), nullable=True),
    sa.Column('state_snapshot', _json_document(), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_workflow_runs_thread_id'))
    )
    op.create_index(op.f('ix_workflow_runs_organization_unit_id'), 'workflow_runs', ['organization_unit_id'], unique=False)
    op.create_index('ix_workflow_runs_status_updated', 'workflow_runs', ['status', 'updated_at'], unique=False)
    op.create_table('abnormality_assessments',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['production_events.id'], name=op.f('fk_abnormality_assessments_event_id_production_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abnormality_assessments'))
    )
    op.create_index('ix_assessment_event_status', 'abnormality_assessments', ['event_id', 'review_status'], unique=False)
    op.create_table('ai_call_logs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model_alias', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_units', sa.Integer(), nullable=True),
    sa.Column('output_units', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], name=op.f('fk_ai_call_logs_job_id_ai_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_call_logs'))
    )
    op.create_index('ix_ai_call_logs_job', 'ai_call_logs', ['job_id', 'created_at'], unique=False)
    op.create_table('audio_transcript_versions',
    sa.Column('audio_record_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audio_record_id'], ['audio_records.id'], name=op.f('fk_audio_transcript_versions_audio_record_id_audio_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_transcript_versions')),
    sa.UniqueConstraint('audio_record_id', 'version', name='uq_audio_transcript_version')
    )
    op.create_index(op.f('ix_audio_transcript_versions_audio_record_id'), 'audio_transcript_versions', ['audio_record_id'], unique=False)
    op.create_table('event_source_links',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_locator', _json_document(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['production_events.id'], name=op.f('fk_event_source_links_event_id_production_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_source_links')),
    sa.UniqueConstraint('event_id', 'source_type', 'source_id', name='uq_event_source_link')
    )
    op.create_index(op.f('ix_event_source_links_event_id'), 'event_source_links', ['event_id'], unique=False)
    op.create_table('inspection_images',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('protected_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_records.id'], name=op.f('fk_inspection_images_inspection_id_inspection_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_images')),
    sa.UniqueConstraint('object_key', name=op.f('uq_inspection_images_object_key'))
    )
    op.create_index('ix_inspection_images_record_status', 'inspection_images', ['inspection_id', 'status'], unique=False)
    op.create_table('job_events',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload', _json_document(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], name=op.f('fk_job_events_job_id_ai_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_index('ix_job_events_job_created', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_table('manual_operation_record_versions',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', _json_document(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['manual_operation_records.id'], name=op.f('fk_manual_operation_record_versions_record_id_manual_operation_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_operation_record_versions')),
    sa.UniqueConstraint('record_id', 'version', name='uq_manual_operation_record_version')
    )
    op.create_table('production_event_versions',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('structured_data', _json_document(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['production_events.id'], name=op.f('fk_production_event_versions_event_id_production_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_event_versions')),
    sa.UniqueConstraint('event_id', 'version', name='uq_production_event_version')
    )
    op.create_index(op.f('ix_production_event_versions_event_id'), 'production_event_versions', ['event_id'], unique=False)
    op.create_table('report_versions',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', _json_document(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['operation_reports.id'], name=op.f('fk_report_versions_report_id_operation_reports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_versions')),
    sa.UniqueConstraint('report_id', 'version', name='uq_report_version')
    )
    op.create_index(op.f('ix_report_versions_report_id'), 'report_versions', ['report_id'], unique=False)
    op.create_table('task_outbox',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('operation_key', sa.String(length=200), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('queue', sa.String(length=60), nullable=False),
    sa.Column('payload', _json_document(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], name=op.f('fk_task_outbox_job_id_ai_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_outbox')),
    sa.UniqueConstraint('job_id', 'operation_key', name='uq_task_outbox_operation')
    )
    op.create_index('ix_task_outbox_publish', 'task_outbox', ['status', 'available_at'], unique=False)
    op.create_table('user_accounts',
    sa.Column('external_subject', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('attributes', _json_document(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], name=op.f('fk_user_accounts_organization_unit_id_organization_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_accounts')),
    sa.UniqueConstraint('external_subject', name=op.f('uq_user_accounts_external_subject')),
    sa.UniqueConstraint('username', name=op.f('uq_user_accounts_username'))
    )
    op.create_index(op.f('ix_user_accounts_organization_unit_id'), 'user_accounts', ['organization_unit_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('organization_unit_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('source_workflow_run_id', sa.Uuid(), nullable=False),
    sa.Column('order_no', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['production_events.id'], name=op.f('fk_work_orders_event_id_production_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_work_orders_source_workflow_run_id_workflow_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('order_no', name=op.f('uq_work_orders_order_no')),
    sa.UniqueConstraint('source_workflow_run_id', name='uq_work_order_workflow')
    )
    op.create_index('ix_work_orders_org_status', 'work_orders', ['organization_unit_id', 'status'], unique=False)
    op.create_table('audio_transcript_segments',
    sa.Column('transcript_version_id', sa.Uuid(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker_label', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['audio_transcript_versions.id'], name=op.f('fk_audio_transcript_segments_transcript_version_id_audio_transcript_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_transcript_segments')),
    sa.UniqueConstraint('transcript_version_id', 'segment_index', name='uq_transcript_segment')
    )
    op.create_index('ix_transcript_segments_time', 'audio_transcript_segments', ['transcript_version_id', 'start_ms', 'end_ms'], unique=False)
    op.create_table('handover_summary_versions',
    sa.Column('audio_record_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_version_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('content', _json_document(), nullable=False),
    sa.Column('source_segment_ids', _json_document(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audio_record_id'], ['audio_records.id'], name=op.f('fk_handover_summary_versions_audio_record_id_audio_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transcript_version_id'], ['audio_transcript_versions.id'], name=op.f('fk_handover_summary_versions_transcript_version_id_audio_transcript_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handover_summary_versions')),
    sa.UniqueConstraint('audio_record_id', 'version', name='uq_handover_summary_version')
    )
    op.create_index(op.f('ix_handover_summary_versions_audio_record_id'), 'handover_summary_versions', ['audio_record_id'], unique=False)
    op.create_table('inspection_findings',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], name=op.f('fk_inspection_findings_image_id_inspection_images'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_records.id'], name=op.f('fk_inspection_findings_inspection_id_inspection_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_findings'))
    )
    op.create_index('ix_findings_inspection_status', 'inspection_findings', ['inspection_id', 'review_status'], unique=False)
    op.create_table('report_exports',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('report_version_id', sa.Uuid(), nullable=False),
    sa.Column('export_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['operation_reports.id'], name=op.f('fk_report_exports_report_id_operation_reports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], name=op.f('fk_report_exports_report_version_id_report_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_exports'))
    )
    op.create_index('ix_report_exports_report_status', 'report_exports', ['report_id', 'status'], unique=False)
    op.create_table('report_sources',
    sa.Column('report_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot', _json_document(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], name=op.f('fk_report_sources_report_version_id_report_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_sources')),
    sa.UniqueConstraint('report_version_id', 'source_type', 'source_id', name='uq_report_source')
    )
    op.create_index(op.f('ix_report_sources_report_version_id'), 'report_sources', ['report_version_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('data_scope', _json_document(), nullable=False),
    sa.Column('scope_digest', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role_definitions.id'], name=op.f('fk_role_assignments_role_id_role_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('fk_role_assignments_user_id_user_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignments')),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_digest', name='uq_role_assignment_scope')
    )
    op.create_index('ix_role_assignments_user_active', 'role_assignments', ['user_id', 'active'], unique=False)
    op.create_table('work_order_attachments',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_attachments_work_order_id_work_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_attachments')),
    sa.UniqueConstraint('object_key', name=op.f('uq_work_order_attachments_object_key'))
    )
    op.create_index(op.f('ix_work_order_attachments_work_order_id'), 'work_order_attachments', ['work_order_id'], unique=False)
    op.create_table('work_order_reminders',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('reminder_type', sa.String(length=40), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', _json_document(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_reminders_work_order_id_work_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_reminders')),
    sa.UniqueConstraint('work_order_id', 'reminder_type', 'scheduled_at', name='uq_work_order_reminder')
    )
    op.create_index(op.f('ix_work_order_reminders_work_order_id'), 'work_order_reminders', ['work_order_id'], unique=False)
    op.create_table('work_order_transitions',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_after', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_transitions_work_order_id_work_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_transitions'))
    )
    op.create_index('ix_work_order_transition_time', 'work_order_transitions', ['work_order_id', 'occurred_at'], unique=False)
    op.create_table('inspection_finding_links',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['inspection_findings.id'], name=op.f('fk_inspection_finding_links_finding_id_inspection_findings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_finding_links')),
    sa.UniqueConstraint('finding_id', 'target_type', 'target_id', 'active', name='uq_finding_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_finding_links')
    op.drop_index('ix_work_order_transition_time', table_name='work_order_transitions')
    op.drop_table('work_order_transitions')
    op.drop_index(op.f('ix_work_order_reminders_work_order_id'), table_name='work_order_reminders')
    op.drop_table('work_order_reminders')
    op.drop_index(op.f('ix_work_order_attachments_work_order_id'), table_name='work_order_attachments')
    op.drop_table('work_order_attachments')
    op.drop_index('ix_role_assignments_user_active', table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_report_sources_report_version_id'), table_name='report_sources')
    op.drop_table('report_sources')
    op.drop_index('ix_report_exports_report_status', table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index('ix_findings_inspection_status', table_name='inspection_findings')
    op.drop_table('inspection_findings')
    op.drop_index(op.f('ix_handover_summary_versions_audio_record_id'), table_name='handover_summary_versions')
    op.drop_table('handover_summary_versions')
    op.drop_index('ix_transcript_segments_time', table_name='audio_transcript_segments')
    op.drop_table('audio_transcript_segments')
    op.drop_index('ix_work_orders_org_status', table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_user_accounts_organization_unit_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index('ix_task_outbox_publish', table_name='task_outbox')
    op.drop_table('task_outbox')
    op.drop_index(op.f('ix_report_versions_report_id'), table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index(op.f('ix_production_event_versions_event_id'), table_name='production_event_versions')
    op.drop_table('production_event_versions')
    op.drop_table('manual_operation_record_versions')
    op.drop_index('ix_job_events_job_created', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_inspection_images_record_status', table_name='inspection_images')
    op.drop_table('inspection_images')
    op.drop_index(op.f('ix_event_source_links_event_id'), table_name='event_source_links')
    op.drop_table('event_source_links')
    op.drop_index(op.f('ix_audio_transcript_versions_audio_record_id'), table_name='audio_transcript_versions')
    op.drop_table('audio_transcript_versions')
    op.drop_index('ix_ai_call_logs_job', table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    op.drop_index('ix_assessment_event_status', table_name='abnormality_assessments')
    op.drop_table('abnormality_assessments')
    op.drop_index('ix_workflow_runs_status_updated', table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_organization_unit_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_upload_sessions_status'), table_name='upload_sessions')
    op.drop_index('ix_upload_sessions_resource', table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_organization_unit_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_table('role_definitions')
    op.drop_index(op.f('ix_prompt_template_versions_template_code'), table_name='prompt_template_versions')
    op.drop_table('prompt_template_versions')
    op.drop_index('ix_production_events_status', table_name='production_events')
    op.drop_index('ix_production_events_org_time', table_name='production_events')
    op.drop_index(op.f('ix_production_events_event_type'), table_name='production_events')
    op.drop_table('production_events')
    op.drop_index(op.f('ix_organization_units_path'), table_name='organization_units')
    op.drop_table('organization_units')
    op.drop_index('ix_operation_reports_status', table_name='operation_reports')
    op.drop_table('operation_reports')
    op.drop_table('model_aliases')
    op.drop_index('ix_manual_operation_org_time', table_name='manual_operation_records')
    op.drop_table('manual_operation_records')
    op.drop_index('ix_inspection_org_time', table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_business_config_versions_config_code'), table_name='business_config_versions')
    op.drop_table('business_config_versions')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_unit_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_audio_records_org_shift', table_name='audio_records')
    op.drop_table('audio_records')
    op.drop_index('ix_ai_jobs_status_updated', table_name='ai_jobs')
    op.drop_index('ix_ai_jobs_resource', table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_organization_unit_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
